### ISSUE TITLE
Please add languages plsql, and possibly also oracle sql

### ISSUE THREAD

**Issue by jayvdb** [jcdavison/antipattern#30]
plsql is a very specific language.

Also would be useful to allow watching of specific dialects of languages, such as 'oracle sql', but there are many dialects of many languages, and adding them as languages would create an unwieldy language list.  This may be what you're thinking of in #6

**Comment by jcdavison** [comment]
https://www.dropbox.com/s/54xztssobfurnkn/Screenshot%202015-12-02%2013.33.43.png?dl=0

done
