### ISSUE TITLE
non open-source code shouldnt be included

### ISSUE THREAD

**Issue by jayvdb** [jcdavison/antipattern#31]
https://www.antipattern.io/code-reviews/40

**Comment by jayvdb** [comment]
probably worth displaying the license and asking the requester to confirm it before creating the review.

**Comment by jcdavison** [comment]
@jayvdb what makes you think the code posted was not open source code?  

I otherwise agree with you on all fronts that no open source code should be posted and I am operating under the assumption that this application doesn't have access to people's private code.

**Comment by jayvdb** [comment]
"All rights reserved."
https://en.wikipedia.org/wiki/All_rights_reserved

**Comment by jayvdb** [comment]
That commit was merged into the main repo
https://github.com/carouselapps/ninjatools/blob/master/resources/migrations/20151106134834-fix-indexes-and-fields.down.sql
And the main repo also states All rights reserved.
https://github.com/carouselapps/ninjatools/blob/master/README.md#license

**Comment by jcdavison** [comment]
i'm gonna close this as it is some kind of user issue, if a  user has code they think is private only then the code shouldn't be in a public facing repo.  the real issue at hand here is attribution to someone else's code, that is a higher level problem for me and respecting developers works according to whatever standards they desire is part of the terms of service for the site, which I need to document accordingly and I have an open issue to do that :)
